:concurrency: 3
:timeout: 60
:verbose: true
:queues:  # Queue priority: https://github.com/mperham/sidekiq/wiki/Advanced-Options
  - default
  - mailers
:schedule:
  RecomfirmJob:
    cron: '0 0 * * *'
    queue: scheduler
    enabled: true
  EmptyingJob:
    cron: '0 0 * * *'
    queue: scheduler
    enabled: true